### PR TITLE
Swift 4 and RxSwift 4 update

### PR DESCRIPTION
**Pull request by pedrommcarrasco**
Updated RxStarscream to Swift 4 and RxSwift 4 updates. Including the Sample App.

### CODE REVIEW

**Comment by freak4pc** [comment]
Hey @pedrommcarrasco , Thanks for this !
Do you mind rebasing on top of master?

Since the CI was fixed since and I want to make sure the RxSwift 4 updates doesn't break the tests. 

Thanks !

**Comment by pedrommcarrasco** [comment]
@freak4pc was nothing :)The following week will be a busy one, but sure, I would do it as soon as possible.

**Comment by freak4pc** [comment]
@pedrommcarrasco 

It should be as easy as a 
```
git rebase master
git push -fu origin
```

No rush though !

**Comment by pedrommcarrasco** [comment]
@freak4pc according to the following image seems that nothing broke. (Went to my fork's rxstarscream folder and ran both commands).
captura de ecra 2018-01-01 as 21 36 52

Excuse me if this was not what you meant.

**Comment by freak4pc** [comment]
You need to pull RxSwiftCommunity's master to your master before rebasing - you have an outdated master. Another option (easier), just add this file to your root folder: https://github.com/RxSwiftCommunity/RxStarscream/blob/master/circle.yml

**Comment by freak4pc** [comment]
@pedrommcarrasco Do you mind opening a new PR instead of this one? I'm not sure why but there is something weird going on and it's not triggering the CI. Would make both our lives easier :) Thanks.

**Comment by pedrommcarrasco** [comment]
@freak4pc Sure

**Pull request closed without merging**
