### PR TITLE
migrate to Starscream==4

### PR DESCRIPTION
**Pull request by michaelhenry**

### CODE REVIEW

**Comment by michaelhenry** [comment]
@freak4pc please review. Thanks

**Comment by freak4pc** [comment]
Hey @michaelhenry. I'm not the maintainer of this project, the community is... In  general, since we all do this in our spare time, its advised to not tag individual members. Thanks for understanding!

**Comment by michaelhenry** [comment]
@freak4pc Oh sorry, Thanks for your response.

**Comment by michaelhenry** [comment]
for those who want to use the latest Starscream and RxSwift please use this forked repo

```ruby
pod 'RxStarscream', :git => 'https://github.com/NiftyStack/RxStarscream'
```

**Pull request closed without merging**
