### PR TITLE
Support OSX

### PR DESCRIPTION
**Pull request by yysskk**
## Reference 
- [Starscream.podspec](https://github.com/daltoniam/Starscream/blob/master/Starscream.podspec)
- [RxSwift.podspec](https://github.com/ReactiveX/RxSwift/blob/master/RxSwift.podspec)

### CODE REVIEW

**Comment by pedrommcarrasco** [comment]
Seems like a god one, @freak4pc what do you think?

**Comment by freak4pc** [comment]
Thanks @yysskk. 
Could you please add a build test for macOS on our CI?

**Comment by yysskk** [comment]
@freak4pc I added a macOS target for CI build (https://github.com/RxSwiftCommunity/RxStarscream/pull/18/commits/7f4abc20f4dd5c120939e2d83379edd9f341b041) and a build test for macOS(https://github.com/RxSwiftCommunity/RxStarscream/pull/18/commits/ca5b713f9d99bc02c2f3924a66090887f8d40a3a) 👍

**Comment by freak4pc** [comment]
Looks great ! Let me review this by tomorrow and I’ll merge :)

**Comment by yysskk** [comment]
@freak4pc merge, ok?

**Review by freak4pc — APPROVED** [review]
Looks good ! Sorry for the delay :)

**Pull request merged**
